NDefines.NGame.END_DATE = "1960.1.1.1";
-- NDefines.NFocus.FOCUS_POINT_DAYS = 15;
NDefines.NBuildings.MAX_SHARED_SLOTS = 40;
NDefines.NMilitary.PLAYER_ORDER_PLANNING_DECAY = 0.02;
NDefines.NNavy.NAVAL_SUPREMACY_CAN_INVADE = 0.4;
NDefines.NProduction.CAPITAL_SHIP_MAX_NAV_FACTORIES_PER_LINE = 10;

NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_LOW = 0.85;
NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_LOW = 0.85;
NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_MED = 0.65;
NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_MED = 0.65;
NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_HIGH = 0.5;
NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_HIGH = 0.5;
